Repository kowala-tech/kcoin, pull requests merged in 2018-08, with the labels that each got.

#643 fix consensus algorithm
  client/core/blockchain.go
  client/core/headerchain.go
  client/core/types/receipt.go
Labels: needs more reviews

#674 Licenses added to the root of the project
  LICENSE.ENS
  LICENSE.ETHEREUM
  LICENSE.KOWALA-SMART-CONTRACTS
  LICENSE.md
  client/contracts/truffle/contracts/licenses/Master License
Labels: High priority, andromeda-launch

#682 Lower default log verbosity
  client/internal/debug/flags.go
Labels: andromeda-launch

#690 Migrated tests to truffle framework
  client/contracts/bindings/consensus/build/CappedToken.abi
  client/contracts/bindings/consensus/build/CappedToken.bin
  client/contracts/bindings/consensus/build/KRC223.abi
  client/contracts/bindings/consensus/build/MiningToken.abi
  client/contracts/bindings/consensus/build/MiningToken.bin
  client/contracts/bindings/consensus/build/MintableToken.abi
  client/contracts/bindings/consensus/build/MintableToken.bin
  client/contracts/bindings/consensus/build/Pausable.bin
  client/contracts/bindings/consensus/build/SafeMath.bin
  client/contracts/bindings/consensus/build/Token.abi
  client/contracts/bindings/consensus/build/Token.bin
  client/contracts/bindings/consensus/build/ValidatorMgr.bin
  client/contracts/bindings/consensus/gen_manager.go
  client/contracts/bindings/consensus/gen_mtoken.go
  client/contracts/bindings/consensus/testfiles/build/KRC223.abi
  client/contracts/bindings/consensus/testfiles/build/Pausable.bin
  client/contracts/bindings/consensus/testfiles/build/ValidatorMgr.bin
  client/contracts/bindings/consensus/testfiles/gen_validator.go
  client/contracts/bindings/oracle/build/OracleMgr.bin
  client/contracts/bindings/oracle/build/Pausable.bin
  client/contracts/bindings/oracle/gen_manager.go
  client/contracts/bindings/oracle/testfiles/build/OracleMgr.bin
  client/contracts/bindings/oracle/testfiles/build/Pausable.bin
  client/contracts/bindings/oracle/testfiles/gen_manager.go
  client/contracts/bindings/proxy/build/AddressUtils.bin
  client/contracts/bindings/proxy/build/AdminUpgradeabilityProxy.bin
  client/contracts/bindings/proxy/build/UpgradeabilityProxy.bin
  client/contracts/bindings/proxy/build/UpgradeabilityProxyFactory.bin
  client/contracts/bindings/proxy/gen_manager.go
  client/contracts/bindings/stability/build/Pausable.bin
  client/contracts/bindings/stability/build/Stability.bin
  client/contracts/bindings/stability/gen_stability.go
  client/contracts/bindings/sysvars/build/Math.bin
  client/contracts/bindings/sysvars/build/SystemVars.bin
  client/contracts/bindings/sysvars/gen_systemvars.go
  client/contracts/truffle/contracts/oracle/OracleMgr.sol
  client/contracts/truffle/contracts/test/BalanceContract.sol
  client/contracts/truffle/contracts/test/DomainResolverMock.sol
  client/contracts/truffle/contracts/token/KRC223.sol
  client/contracts/truffle/contracts/token/Token.sol
  client/contracts/truffle/migrations/2_deploy_contracts.js
  client/contracts/truffle/package-lock.json
  client/contracts/truffle/package.json
  client/contracts/truffle/test/helpers/testUtils.js
  client/contracts/truffle/test/kns/KNSFunctionality.test.js
  client/contracts/truffle/test/oracle/OracleMgr.test.js
  client/contracts/truffle/test/ownership/MultiSigWallet.test.js
  client/contracts/truffle/test/proxy/Proxy.test.js
  client/contracts/truffle/test/stability/Stability.test.js
  client/contracts/truffle/test/systemvars/SystemVars.test.js
  client/contracts/truffle/test/token/Token.test.js
  client/contracts/truffle/test/validator/ValidatorMgr.test.js
  client/contracts/truffle/truffle.js
  client/knode/genesis/testfiles/genesis.json.golden
Labels: andromeda-launch, blocked, enhancement

#700 Improved console minting tools
  client/internal/web3ext/web3ext.go
  client/knode/api.go
Labels: andromeda-launch

#701 Main net wallet tools
  wallet-tools/app/scripts/nodes.js
Labels: andromeda-launch
