Repository kowala-tech/kcoin, pull requests merged in 2018-10, with the labels that each got.

#809 Feature/exchangemgr tests
  client/contracts/bindings/oracle/build/ExchangeMgr.bin
  client/contracts/bindings/oracle/gen_exchange.go
  client/contracts/bindings/oracle/testfiles/build/ExchangeMgr.bin
  client/contracts/bindings/oracle/testfiles/gen_exchange.go
  client/contracts/truffle/contracts/oracle/ExchangeMgr.sol
  client/contracts/truffle/package-lock.json
  client/contracts/truffle/package.json
  client/contracts/truffle/test/oracle/ExchangeMgr.test.js
Labels: enhancement

#799 Added docs for the Solidity code
  .drone.yml
  Makefile
  client/contracts/bindings/oracle/build/ExchangeMgr.bin
  client/contracts/bindings/oracle/gen_exchange.go
  client/contracts/bindings/oracle/testfiles/build/ExchangeMgr.bin
  client/contracts/bindings/oracle/testfiles/gen_exchange.go
  client/contracts/truffle/README.md
  client/contracts/truffle/contracts/oracle/ExchangeMgr.sol
  docs/docs/smartcontracts/BalanceContract.md
  docs/docs/smartcontracts/CappedToken.md
  docs/docs/smartcontracts/Consensus.md
  docs/docs/smartcontracts/ConsensusMock.md
  docs/docs/smartcontracts/DomainResolver.md
  docs/docs/smartcontracts/DomainResolverMock.md
  docs/docs/smartcontracts/ExchangeMgr.md
  docs/docs/smartcontracts/FIFSRegistrar.md
  docs/docs/smartcontracts/Initializable.md
  docs/docs/smartcontracts/KNS.md
  docs/docs/smartcontracts/KNSRegistry.md
  docs/docs/smartcontracts/KNSRegistryV1.md
  docs/docs/smartcontracts/KRC223.md
  docs/docs/smartcontracts/Math.md
  docs/docs/smartcontracts/Migrations.md
  docs/docs/smartcontracts/MiningToken.md
  docs/docs/smartcontracts/MintableToken.md
  docs/docs/smartcontracts/MultiSigWallet.md
  docs/docs/smartcontracts/NameHash.md
  docs/docs/smartcontracts/OracleMgr.md
  docs/docs/smartcontracts/Ownable.md
  docs/docs/smartcontracts/Pausable.md
  docs/docs/smartcontracts/PriceProvider.md
  docs/docs/smartcontracts/PublicResolver.md
  docs/docs/smartcontracts/SafeMath.md
  docs/docs/smartcontracts/Stability.md
  docs/docs/smartcontracts/SystemVars.md
  docs/docs/smartcontracts/Token.md
  docs/docs/smartcontracts/TokenMock.md
  docs/docs/smartcontracts/TokenReceiver.md
  docs/docs/smartcontracts/ValidatorMgr.md
  docs/docs/smartcontracts/strings.md
  docs/mkdocs.yml
Labels: enhancement

#826 Implemented genesis freeze
  .drone.yml
  Makefile
  client/cmd/genesisgen/main.go
  client/knode/genesis/kusd_generated.go
  client/knode/genesis/loader.go
  client/knode/genesis/networks.go
Labels: WIP

#813 Removed Stability contract and all of its references
  client/build/ci.go
  client/contracts/bindings/stability/build/Initializable.abi
  client/contracts/bindings/stability/build/Initializable.bin
  client/contracts/bindings/stability/build/Ownable.abi
  client/contracts/bindings/stability/build/Ownable.bin
  client/contracts/bindings/stability/build/Pausable.abi
  client/contracts/bindings/stability/build/Pausable.bin
  client/contracts/bindings/stability/build/PriceProvider.abi
  client/contracts/bindings/stability/build/PriceProvider.bin
  client/contracts/bindings/stability/build/Stability.abi
  client/contracts/bindings/stability/build/Stability.bin
  client/contracts/bindings/stability/contract.go
  client/contracts/bindings/stability/gen_stability.go
  client/contracts/bindings/stability/stability_test.go
  client/contracts/bindings/stability/testfiles/build/PriceProviderMock.abi
  client/contracts/bindings/stability/testfiles/build/PriceProviderMock.bin
  client/contracts/bindings/stability/testfiles/contracts/PriceProviderMock.sol
  client/contracts/bindings/stability/testfiles/gen_priceprovidermock.go
  client/contracts/bindings/stability/testfiles/test.go
  client/contracts/truffle/contracts/stability/PriceProvider.sol
  client/contracts/truffle/contracts/stability/Stability.sol
  client/contracts/truffle/test/stability/Stability.test.js
  client/knode/genesis/contracts.go
  client/knode/genesis/generator.go
  client/knode/genesis/loader_test.go
  client/knode/genesis/options.go
  client/knode/genesis/testfiles/genesis.json.golden
  client/knode/service.go
  docs/docs/smartcontracts/BalanceContract.md
  docs/docs/smartcontracts/CappedToken.md
  docs/docs/smartcontracts/Consensus.md
  docs/docs/smartcontracts/ConsensusMock.md
  docs/docs/smartcontracts/DomainResolver.md
  docs/docs/smartcontracts/DomainResolverMock.md
  docs/docs/smartcontracts/ExchangeMgr.md
  docs/docs/smartcontracts/FIFSRegistrar.md
  docs/docs/smartcontracts/Initializable.md
  docs/docs/smartcontracts/KNS.md
  docs/docs/smartcontracts/KNSRegistry.md
  docs/docs/smartcontracts/KNSRegistryV1.md
  docs/docs/smartcontracts/KRC223.md
  docs/docs/smartcontracts/Math.md
  docs/docs/smartcontracts/Migrations.md
  docs/docs/smartcontracts/MiningToken.md
  docs/docs/smartcontracts/MintableToken.md
  docs/docs/smartcontracts/MultiSigWallet.md
  docs/docs/smartcontracts/NameHash.md
  docs/docs/smartcontracts/OracleMgr.md
  docs/docs/smartcontracts/Ownable.md
  docs/docs/smartcontracts/Pausable.md
  docs/docs/smartcontracts/PriceProvider.md
  docs/docs/smartcontracts/PublicResolver.md
  docs/docs/smartcontracts/SafeMath.md
  docs/docs/smartcontracts/Stability.md
  docs/docs/smartcontracts/SystemVars.md
  docs/docs/smartcontracts/Token.md
  docs/docs/smartcontracts/TokenMock.md
  docs/docs/smartcontracts/TokenReceiver.md
  docs/docs/smartcontracts/ValidatorMgr.md
  docs/docs/smartcontracts/strings.md
Labels: blocked
